export const SHOW__PROJECT = "SHOW__PROJECT";
export const ADD__PROJECT = "ADD__PROJECT";
export const VALIDATE__FORM = "VALIDATE__FORM";
export const CURRENT__PROJECT = "CURRENT__PROJECT";
export const DELETE__PROJECT = "DELETE__PROJECT";

export const ADD__TASK = "ADD__TASK";
export const FILTER__PROJECT__TASK = "FILTER__PROJECT__TASK";
export const VALIDATE__FORM__TASK = "VALIDATE__FORM__TASK";
export const DELETE__TASK = "DELETE__TASK";
export const CHANGE__STATE__TASK = "CHANGE__STATE__TASK";
export const CHANGE__SELECTED__TASK = "CHANGE__SELECTED__TASK";
export const MODIFY__SELECTED__TASK = "MODIFY__SELECTED__TASK";

export const SHOW__ALERT = "SHOW__ALERT";
export const HIDE__ALERT = "HIDE__ALERT";

export const SUCCESS__REGISTER = "SUCCESS__REGISTER";
export const ERROR__REGISTER = "ERROR__REGISTER";

export const GET__AUTHENTICATED__USER = "GET__AUTHENTICATED__USER";

export const GET__AUTHENTICATED__USER__ERROR = "GET__AUTHENTICATED__USER__ERROR";
export const LOGIN__USER = "LOGIN__USER";
export const LOGIN__USER__ERROR = "LOGIN__USER__ERROR";
export const LOGOUT__USER = "LOGOUT__USER";